Output vhs.gif
Set FontSize 30
Set Width 1920
Set Height 1080

Sleep 1s
Type "futbin nations | grep -i braz"
Enter

Sleep 1s
Type "futbin players --nation 54"
Enter

Sleep 1s
Type "futbin players --nation 54 --skills 5"
Enter

Sleep 1s
Type "futbin players --nation 54 --skills 5 --price -1000000"
Enter

Sleep 1s
Type "futbin players --nation 54 --skills 5 --price -1000000 --wf 4-"
Enter

Sleep 1s
Type "futbin players --nation 54 --skills 5 --price -1000000 --wf 4- --pace 87-90"
Enter


Sleep 2s